/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * 搜索结果 (返回 ID 而非 Tag 文本)
 * 上层 JS 会拿着 ID 去 SQLite 里查具体的文本内容
 */
export interface SearchResult {
  id: number
  score: number
}
/** 统计信息 */
export interface VexusStats {
  totalVectors: number
  dimensions: number
  capacity: number
  memoryUsage: number
}
/** 核心索引结构 (无状态，只存向量) */
export declare class VexusIndex {
  /** 创建新的空索引 */
  constructor(dim: number, capacity: number)
  /**
   * 从磁盘加载索引
   * 注意：移除了 map_path，因为映射关系现在由 SQLite 管理
   */
  static load(indexPath: string, unusedMapPath: string | undefined | null, dim: number, capacity: number): VexusIndex
  /** 保存索引到磁盘 */
  save(indexPath: string): void
  /** 单个添加 (JS 循环调用) */
  add(id: number, vector: Buffer): void
  /** 批量添加 (更高效，建议未来 JS 改用此接口) */
  addBatch(ids: Array<number>, vectors: Buffer): void
  /** 搜索 */
  search(query: Buffer, k: number): Array<SearchResult>
  /** 删除 (按 ID) */
  remove(id: number): void
  /** 获取当前索引状态 */
  stats(): VexusStats
  /** 从 SQLite 数据库恢复索引 (异步版本，不阻塞主线程) */
  recoverFromSqlite(dbPath: string, tableType: string, filterDiaryName?: string | undefined | null): Promise<unknown>
}
