/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 搜索结果 */
export interface SearchResult {
  tag: string
  score: number
}
/** 统计信息 */
export interface VexusStats {
  totalVectors: number
  dimensions: number
  capacity: number
}
/** 核心索引结构 */
export declare class VexusIndex {
  /** 创建新的空索引 */
  constructor(dim: number, capacity: number)
  /** ✅ 修复：从磁盘加载索引（增加capacity参数） */
  static load(indexPath: string, mapPath: string, dim: number, capacity: number): VexusIndex
  /** 保存到磁盘 */
  save(indexPath: string, mapPath: string): void
  /** ✅ 修复：批量添加/更新向量（增加容量检查和自动扩容） */
  upsert(tags: Array<string>, vectors: Buffer): void
  /** 快速搜索 */
  search(query: Buffer, k: number): Array<SearchResult>
  /** 删除tags */
  remove(tags: Array<string>): void
  /** 获取统计信息 */
  stats(): VexusStats
}
